spring.application.name=spotifytools

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_UN}
spring.datasource.password=${DB_PW}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spotify.clientId=${SPOT_ID}
spotify.clientSecret=${SPOT_SECRET}

redirect.server.ip=${SPOT_REDIRECT}